### ISSUE TITLE
chunk根本用不了

### ISSUE THREAD

**Issue by pinkyaliceyym** [stevewyl/nlp_toolkit#1]
为什么我把你的chunk代码原封不动的搬到python3里，运行不出来分词结果啊？

下面是报错的信息，提示gpu_no数组溢出？

Using TensorFlow backend.
Traceback (most recent call last):
  File "D:/Alice Study/PythonProject/readembeddingfile.py", line 1, in <module>
    from nlp_toolkit.chunk_segmentor import Chunk_Segmentor
  File "D:\Alice Software\python3\lib\site-packages\nlp_toolkit\__init__.py", line 21, in <module>
    gpu_no = str(avail_gpu[0])
IndexError: list index out of range

**Comment by stevewyl** [comment]
@pinkyaliceyym 首先你没有chunk的模型和字典数据，肯定跑不出结果的，因为是公司内部的数据，暂时不方便给到。另外，这个错误可能是你没有可用的gpu设备导致的

**Comment by pinkyaliceyym** [comment]
那看来我是用不上了……




| |
杨雨萌
邮箱：yumengyangpku@163.com
|

签名由 网易邮箱大师 定制

在2019年01月04日 18:58，stevewyl 写道：

@pinkyaliceyym 首先你没有chunk的模型和字典数据，肯定跑不出结果的，因为是公司内部的数据，暂时不方便给到。另外，这个错误可能是你没有可用的gpu设备导致的
